### ISSUE TITLE
Code and model weights are not released yet

### ISSUE THREAD

**Issue by ShivamSRS** [sist-soolab/FreeBloom#1]
Please release the code and weights of the model

**Comment by ShivamSRS** [comment]
Where are the diffusion model weights? The readme says to add the path of the same to configs in the yaml file @JudgementH

**Comment by JudgementH** [comment]
The pre-trained Stable Diffusion models can be downloaded from Hugging Face (e.g. https://huggingface.co/runwayml/stable-diffusion-v1-5 ).  

For example, you can direcly add the huggingface repository into the configs
```
pretrained_model_path: "runwayml/stable-diffusion-v1-5"
```

You can also download the weights to a local path e.g. "/data/diffusion_wights/stable-diffusion-v1-5"
```
pretrained_model_path: "/data/diffusion_wights/stable-diffusion-v1-5"
```
