### ISSUE TITLE
Code about Interpolation empowerment module

### ISSUE THREAD

**Issue by ShawnChenn** [sist-soolab/FreeBloom#4]
Hi, thanks for your wonderful works on long video generation. But could you figure out whether the code corresponding to `` Interpolation empowerment module" has been released or not?

**Comment by FatLong666** [comment]
I also have the same problems with U, hope the author can share some useful information  with us ! Best wish!

**Comment by JudgementH** [comment]
Hi, you can find interpolation part from here https://github.com/SooLab/Free-Bloom/blob/4498b463cb4f1e652912db2144cf8d8983e6e141/freebloom/pipelines/pipeline_spatio_temporal.py#L491-L499

And, I have upload a script [interp.py](https://github.com/SooLab/Free-Bloom/blob/main/interp.py) for easier usage of the interpolation part.
